[tool.poetry]
name = "hacktionary"
version = "0.1.0"
description = ""
authors = ["Erik Tollerud <erik.tollerud@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pelican = "^4.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
